### ISSUE TITLE
Mongo 3.0 support?

### ISSUE THREAD

**Issue by yepelinux** [greenlaw110/play-morphia#131]
Hi, there's any intention of upgrading this library to support mongo 3.0 ?

I'll be pleased to help in that update.

**Comment by greenlaw110** [comment]
Hi at the moment I have no plan on upgrading. But yes please feel free to fork and send me pull request if you can get it done

**Comment by shoon** [comment]
We're running this library in production with Mongo 3 and the wiredTiger storageEngine... we've noted no problems so far (other than Robomongo not working with it)

**Comment by yepelinux** [comment]
@shoon how's your dependencies.yml?

Mine is as follows, and its not working:

require:
    - play 1.3.1
    - com.gelinsoft -> morphia 1.5.0a

repositories:
    - gelinsoft:
        type: http
        artifact: "http://gelinsoft.com/play/repo/[module]-[revision].zip"
        contains:
            - com.gelinsoft -> *

Thanks in advance!

**Comment by yepelinux** [comment]
in my case i cant even connect to mongodb.

16:56:55,896 WARN  ~ You're running Play! in DEV mode
16:56:55,976 INFO  ~ Listening for HTTP on port 9000 (Waiting a first request to start) ...
~ Server is up and running
16:57:32,042 DEBUG ~ MorphiaPlugin-1.5.0> reading configuration
16:57:34,402 ERROR ~ Error al correr el invocationFinally
java.lang.NullPointerException
	at play.modules.morphia.Model$MorphiaQuery.<init>(Model.java:1417)
	at models.WhiteLabel.all(WhiteLabel.java)
	at models.WhiteLabel.findAll(WhiteLabel.java)
	at models.WhiteLabel.getForDomain(WhiteLabel.java:107)
	at plugins.CookieDomainReWriterPlugin.rewriteCookiesDomain(CookieDomainReWriterPlugin.java:25)
	at plugins.CookieDomainReWriterPlugin.onInvocationException(CookieDomainReWriterPlugin.java:43)
	at play.plugins.PluginCollection.onInvocationException(PluginCollection.java:482)
	at play.Invoker$Invocation.onException(Invoker.java:241)
	at play.Invoker$Invocation.run(Invoker.java:305)
	at Invocation.HTTP Request(Play!)
16:57:34,515 ERROR ~ 

@6ndh6mnd0
Internal Server Error (500) for request GET /

Oops: RuntimeException
An unexpected error occured caused by exception RuntimeException: MongoDB authentication failed: convergency_desa_v3

play.exceptions.UnexpectedException: Unexpected Error
	at play.Play.start(Play.java:567)
	at play.Play.detectChanges(Play.java:641)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: MongoDB authentication failed: convergency_desa_v3
	at play.modules.morphia.MorphiaPlugin.initMorphia_(MorphiaPlugin.java:544)
	at play.modules.morphia.MorphiaPlugin.onApplicationStart(MorphiaPlugin.java:696)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:515)
	at play.Play.start(Play.java:537)
	... 3 more
16:58:42,253 ERROR ~ Error al correr el invocationFinally
java.lang.NullPointerException
	at play.modules.morphia.Model$MorphiaQuery.<init>(Model.java:1417)
	at models.WhiteLabel.all(WhiteLabel.java)
	at models.WhiteLabel.findAll(WhiteLabel.java)
	at models.WhiteLabel.getForDomain(WhiteLabel.java:107)
	at plugins.CookieDomainReWriterPlugin.rewriteCookiesDomain(CookieDomainReWriterPlugin.java:25)
	at plugins.CookieDomainReWriterPlugin.onInvocationException(CookieDomainReWriterPlugin.java:43)
	at play.plugins.PluginCollection.onInvocationException(PluginCollection.java:482)
	at play.Invoker$Invocation.onException(Invoker.java:241)
	at play.Invoker$Invocation.run(Invoker.java:305)
	at Invocation.HTTP Request(Play!)
16:58:42,313 ERROR ~ 

@6ndh6mnd1
Internal Server Error (500) for request GET /

Oops: RuntimeException
An unexpected error occured caused by exception RuntimeException: MongoDB authentication failed: convergency_desa_v3

play.exceptions.UnexpectedException: Unexpected Error
	at play.Play.start(Play.java:567)
	at play.Play.detectChanges(Play.java:641)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: MongoDB authentication failed: convergency_desa_v3
	at play.modules.morphia.MorphiaPlugin.initMorphia_(MorphiaPlugin.java:544)
	at play.modules.morphia.MorphiaPlugin.onApplicationStart(MorphiaPlugin.java:696)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:515)
	at play.Play.start(Play.java:537)
	... 3 more

**Comment by greenlaw110** [comment]
Your code failed at here:

```java
        if (!S.empty(username) && !S.empty(password)) {
            if (!db.isAuthenticated() && !db.authenticate(username, password.toCharArray())) {
                throw new RuntimeException("MongoDB authentication failed: " + dbName);
            }
        }
```

Question have you configured the username password correctly?

**Comment by shoon** [comment]
I think it might be the new authentication scheme in 3.0... Try setting this to go back to the old authentication. I just tried it on an auth database and it worked (users were created after the change)
```
use admin;
db.system.version.save({ "_id" : "authSchema", "currentVersion" : 3 })
```

Here's a discussion about this:
https://github.com/paralect/robomongo/issues/766

**Comment by shoon** [comment]
.. and my deps:

I'm using the latest play1 from the 1.3x branch

mongo driver updated from this pull:

https://github.com/greenlaw110/play-morphia/pull/130

**Comment by tonybaroneee** [comment]
+1
